https://www.perplexity.ai/search/9e65c056-41ac-4275-abf3-718ccc0e498d

In [4]:
import pandas as pd

#檔案:相對路徑的寫法
pd.read_csv('./data/台鐵車站資訊.csv')

,stationCode,stationName,name,stationAddrTw,stationTel,gps,haveBike
0,900,基隆,基隆,基隆市仁愛區港西街5號,02-24263743,25.13411 121.73997,Y
1,910,三坑,三坑,基隆市仁愛區德厚里龍安街 206 號,02-24230289,25.12305 121.74202,Y
2,920,八堵,八堵,基隆市暖暖區八南里八堵路 142 號,02-24560841,25.10843 121.72898,Y
3,930,七堵,七堵,基隆市七堵區長興里東新街 2 號,02-24553426,25.09294 121.71415,Y
4,940,百福,百福,基隆市七堵區堵南里明德三路 1 之 1 號,02-24528372,25.07795 121.69379,N
...,...,...,...,...,...,...,...
238,7360,瑞芳,瑞芳,新北市瑞芳區龍潭里明燈路三段 82 號,02-24972033,25.10861 121.80596,Y
239,7361,海科館,海科館,基隆市中正區長潭里,02-24972033,25.13754 121.79997,N
240,7362,八斗子,八斗子,新北市瑞芳區建基路2段121號隔壁 砂子里省道臺 2 線 (與新北市瑞芳區交界處、無站房),02-24972033,25.13545 121.80261,N
241,7380,四腳亭,四腳亭,新北市瑞芳區吉慶里中央路 65 號,02-24579346,25.10283 121.76192,N
242,7390,暖暖,暖暖,基隆市暖暖區暖暖里暖暖街 51 號,02-24972033,25.10224 121.74048,N

In [8]:
#檔案:絕對目錄的寫法
import os
os.path.dirname(os.path.abspath(__name__))

'c:\\Users\\User\\Documents\\github\\Python\\lesson19'

In [10]:
#檔案:絕對目錄的寫法
import os
current_dir = os.path.dirname(os.path.abspath(__name__))
data_dir = os.path.join(current_dir,'data')
csv_filename = '台鐵車站資訊.csv'
csv_path = os.path.join(data_dir,csv_filename)
pd.read_csv(csv_path)

,stationCode,stationName,name,stationAddrTw,stationTel,gps,haveBike
0,900,基隆,基隆,基隆市仁愛區港西街5號,02-24263743,25.13411 121.73997,Y
1,910,三坑,三坑,基隆市仁愛區德厚里龍安街 206 號,02-24230289,25.12305 121.74202,Y
2,920,八堵,八堵,基隆市暖暖區八南里八堵路 142 號,02-24560841,25.10843 121.72898,Y
3,930,七堵,七堵,基隆市七堵區長興里東新街 2 號,02-24553426,25.09294 121.71415,Y
4,940,百福,百福,基隆市七堵區堵南里明德三路 1 之 1 號,02-24528372,25.07795 121.69379,N
...,...,...,...,...,...,...,...
238,7360,瑞芳,瑞芳,新北市瑞芳區龍潭里明燈路三段 82 號,02-24972033,25.10861 121.80596,Y
239,7361,海科館,海科館,基隆市中正區長潭里,02-24972033,25.13754 121.79997,N
240,7362,八斗子,八斗子,新北市瑞芳區建基路2段121號隔壁 砂子里省道臺 2 線 (與新北市瑞芳區交界處、無站房),02-24972033,25.13545 121.80261,N
241,7380,四腳亭,四腳亭,新北市瑞芳區吉慶里中央路 65 號,02-24579346,25.10283 121.76192,N
242,7390,暖暖,暖暖,基隆市暖暖區暖暖里暖暖街 51 號,02-24972033,25.10224 121.74048,N

In [5]:
#檔案:絕對目錄的寫法
import os
current_dir = os.path.dirname(os.path.abspath(__name__))
data_dir = os.path.join(current_dir,'data')
csv_filename = '台鐵車站資訊.csv'
csv_path = os.path.join(data_dir,csv_filename)
station_info = pd.read_csv(csv_path)

In [13]:
csv1_filename = '每日各站進出站人數2020.csv'
csv1_path = os.path.join(data_dir, csv1_filename)

In [14]:
csv1_filename = '每日各站進出站人數2020.csv'
csv1_path = os.path.join(data_dir, csv1_filename)
csv1_path

'c:\\Users\\User\\Documents\\github\\Python\\lesson19\\data\\每日各站進出站人數2020.csv'

In [15]:
csv1_filename = '每日各站進出站人數2020.csv'
csv1_path = os.path.join(data_dir, csv1_filename)
pd.read_csv(csv1_path)

       trnOpDate  staCode  gateInComingCnt  gateOutGoingCnt
0       20200101      900             7552             8154
1       20200101      910             1020             1135
2       20200101      920             1623             1972
3       20200101      930             4130             4813
4       20200101      940             1818             2128
...          ...      ...              ...              ...
86927   20201231     7360             3523             3602
86928   20201231     7361                3               18
86929   20201231     7362               28               34
86930   20201231     7380              609              604
86931   20201231     7390              377              444

[86932 rows x 4 columns]

In [ ]:
csv1_filename = '每日各站進出站人數2020.csv'
csv1_path = os.path.join(data_dir, csv1_filename)
inOut2020_df = pd.read_csv(csv1_path)

In [16]:
inOut2020_merge = pd.merge(inOut2020_df, station_info,how='left',left_on="staCode",right_on="stationCode")
inOut2020_merge

,trnOpDate,staCode,gateInComingCnt,gateOutGoingCnt,stationCode,stationName,name,stationAddrTw,stationTel,gps,haveBike
0,20200101,900,7552,8154,900,基隆,基隆,基隆市仁愛區港西街5號,02-24263743,25.13411 121.73997,Y
1,20200101,910,1020,1135,910,三坑,三坑,基隆市仁愛區德厚里龍安街 206 號,02-24230289,25.12305 121.74202,Y
2,20200101,920,1623,1972,920,八堵,八堵,基隆市暖暖區八南里八堵路 142 號,02-24560841,25.10843 121.72898,Y
3,20200101,930,4130,4813,930,七堵,七堵,基隆市七堵區長興里東新街 2 號,02-24553426,25.09294 121.71415,Y
4,20200101,940,1818,2128,940,百福,百福,基隆市七堵區堵南里明德三路 1 之 1 號,02-24528372,25.07795 121.69379,N
...,...,...,...,...,...,...,...,...,...,...,...
86927,20201231,7360,3523,3602,7360,瑞芳,瑞芳,新北市瑞芳區龍潭里明燈路三段 82 號,02-24972033,25.10861 121.80596,Y
86928,20201231,7361,3,18,7361,海科館,海科館,基隆市中正區長潭里,02-24972033,25.13754 121.79997,N
86929,20201231,7362,28,34,7362,八斗子,八斗子,新北市瑞芳區建基路2段121號隔壁 砂子里省道臺 2 線 (與新北市瑞芳區交界處、無站房),02-24972033,25.13545 121.80261,N
86930,20201231,7380,609,604,7380,四腳亭,四腳亭,新北市瑞芳區吉慶里中央路 65 號,02-24579346,25.10283 121.76192,N
86931,20201231,7390,377,444,7390,暖暖,暖暖,基隆市暖暖區暖暖里暖暖街 51 號,02-24972033,25.10224 121.74048,N

In [7]:
inOut2020_merge = pd.merge(inOut2020_df, station_info,how='left',left_on="staCode",right_on="stationCode")
#清理資料
df1 = inOut2020_merge.reindex(columns=['trnOpDate','gateInComingCnt','gateOutGoingCnt','stationName'])
df1.columns = ['日期','進站人數','出站人數','站名']
df1

             日期  進站人數  出站人數   站名
0      20200101  7552  8154   基隆
1      20200101  1020  1135   三坑
2      20200101  1623  1972   八堵
3      20200101  4130  4813   七堵
4      20200101  1818  2128   百福
...         ...   ...   ...  ...
86927  20201231  3523  3602   瑞芳
86928  20201231     3    18  海科館
86929  20201231    28    34  八斗子
86930  20201231   609   604  四腳亭
86931  20201231   377   444   暖暖

[86932 rows x 4 columns]

In [17]:
type (df1)

pandas.core.frame.DataFrame

In [19]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 86932 entries, 0 to 86931
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   日期      86932 non-null  int64
 1   進站人數    86932 non-null  int64
 2   出站人數    86932 non-null  int64
 3   站名      86932 non-null  object
dtypes: int64(3), object(1)
memory usage: 2.7+ MB

In [21]:
df1['日期'].astype(str).info()

<class 'pandas.core.series.Series'>
RangeIndex: 86932 entries, 0 to 86931
Series name: 日期
Non-Null Count  Dtype
--------------  -----
86932 non-null  object
dtypes: object(1)
memory usage: 679.3+ KB

In [23]:
pd.to_datetime(df1['日期'].astype(str))

0       2020-01-01
1       2020-01-01
2       2020-01-01
3       2020-01-01
4       2020-01-01
           ...
86927   2020-12-31
86928   2020-12-31
86929   2020-12-31
86930   2020-12-31
86931   2020-12-31
Name: 日期, Length: 86932, dtype: datetime64[ns]

In [24]:
df1['日期'] = pd.to_datetime(df1['日期'].astype(str))
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 86932 entries, 0 to 86931
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   日期      86932 non-null  datetime64[ns]
 1   進站人數    86932 non-null  int64
 2   出站人數    86932 non-null  int64
 3   站名      86932 non-null  object
dtypes: datetime64[ns](1), int64(2), object(1)
memory usage: 2.7+ MB

In [25]:
df2 = df1.set_index('日期')
df2

            進站人數  出站人數   站名
日期
2020-01-01  7552  8154   基隆
2020-01-01  1020  1135   三坑
2020-01-01  1623  1972   八堵
2020-01-01  4130  4813   七堵
2020-01-01  1818  2128   百福
...          ...   ...  ...
2020-12-31  3523  3602   瑞芳
2020-12-31     3    18  海科館
2020-12-31    28    34  八斗子
2020-12-31   609   604  四腳亭
2020-12-31   377   444   暖暖

[86932 rows x 3 columns]