In [4]:
import numpy as np
import pandas as pd
scores = np.random.randint(50,101,size=(50, 5))

df = pd.DataFrame(scores,
             columns=["國文","英文","地理","人文","氣候"],
             index=[f"stu{i}"for i in range(1,51)]
             )

df['國文']
df['英文']
df[['國文','地理']]

        國文  地理
stu1    51  89
stu2    84  98
stu3    77  63
stu4    92  79
stu5    81  97
stu6    95  64
stu7    93  94
stu8    59  59
stu9    98  55
stu10   90  82
stu11   68  98
stu12   52  62
stu13   74  80
stu14   88  75
stu15   90  94
stu16   96  80
stu17   90  52
stu18   67  87
stu19   85  81
stu20   69  99
stu21   89  79
stu22   69  89
stu23   89  76
stu24   68  98
stu25   77  57
stu26   79  61
stu27   71  70
stu28   52  96
stu29   63  60
stu30  100  83
stu31   71  53
stu32   63  65
stu33   97  67
stu34   79  55
stu35   79  69
stu36   67  79
stu37   55  89
stu38   74  88
stu39   86  58
stu40   64  71
stu41   58  52
stu42   57  66
stu43   90  90
stu44   51  97
stu45   72  63
stu46   73  85
stu47   67  86
stu48   61  51
stu49   97  56
stu50   62  90

In [8]:
df.loc['stu1']
df.loc[['stu1','stu50']]

       國文  英文  地理  人文  氣候
stu1   51  55  89  51  93
stu50  62  51  90  66  88

In [11]:
sum = df['國文'] + df['英文'] + df['地理'] + df['人文'] + df['氣候']
df['總分'] = sum
mean = sum / 5
df['平均'] = mean
df

        國文   英文  地理   人文   氣候   總分    平均
stu1    51   55  89   51   93  339  67.8
stu2    84   91  98   83   88  444  88.8
stu3    77   59  63   84   75  358  71.6
stu4    92   75  79   91   88  425  85.0
stu5    81   58  97   76   60  372  74.4
stu6    95   76  64   77   89  401  80.2
stu7    93   72  94   70   84  413  82.6
stu8    59   94  59   84   93  389  77.8
stu9    98   99  55   90   78  420  84.0
stu10   90   93  82   55   66  386  77.2
stu11   68   84  98   51   60  361  72.2
stu12   52   61  62   60   63  298  59.6
stu13   74   50  80   76   67  347  69.4
stu14   88   97  75   85   91  436  87.2
stu15   90   94  94   84   99  461  92.2
stu16   96   97  80   93   72  438  87.6
stu17   90   51  52   73   98  364  72.8
stu18   67   90  87   63   54  361  72.2
stu19   85   52  81  100   56  374  74.8
stu20   69  100  99   62   76  406  81.2
stu21   89   91  79   90   65  414  82.8
stu22   69   70  89   96   84  408  81.6
stu23   89  100  76   58   76  399  79.8
stu24   68   84  98   90   76  416  83.2
stu25   77   66  57   80   96  376  75.2
stu26   79   81  61   99   84  404  80.8
stu27   71   51  70   95   61  348  69.6
stu28   52   67  96   78   62  355  71.0
stu29   63   72  60   91   99  385  77.0
stu30  100   62  83   66   77  388  77.6
stu31   71   91  53   84   59  358  71.6
stu32   63   61  65   99   56  344  68.8
stu33   97   67  67   95   96  422  84.4
stu34   79   53  55   97   95  379  75.8
stu35   79   79  69   85   89  401  80.2
stu36   67  100  79   72   69  387  77.4
stu37   55   92  89   62   52  350  70.0
stu38   74   54  88   75   50  341  68.2
stu39   86   80  58   97  100  421  84.2
stu40   64   88  71   66   68  357  71.4
stu41   58   60  52   59   63  292  58.4
stu42   57   76  66   59   55  313  62.6
stu43   90   86  90   82   72  420  84.0
stu44   51   77  97   50   60  335  67.0
stu45   72   55  63   92   64  346  69.2
stu46   73   87  85   99   83  427  85.4
stu47   67   98  86   53   64  368  73.6
stu48   61   88  51   50   67  317  63.4
stu49   97   81  56   91   66  391  78.2
stu50   62   51  90   66   88  357  71.4

In [15]:
df.iloc[:,:5]

        國文   英文  地理   人文   氣候
stu1    51   55  89   51   93
stu2    84   91  98   83   88
stu3    77   59  63   84   75
stu4    92   75  79   91   88
stu5    81   58  97   76   60
stu6    95   76  64   77   89
stu7    93   72  94   70   84
stu8    59   94  59   84   93
stu9    98   99  55   90   78
stu10   90   93  82   55   66
stu11   68   84  98   51   60
stu12   52   61  62   60   63
stu13   74   50  80   76   67
stu14   88   97  75   85   91
stu15   90   94  94   84   99
stu16   96   97  80   93   72
stu17   90   51  52   73   98
stu18   67   90  87   63   54
stu19   85   52  81  100   56
stu20   69  100  99   62   76
stu21   89   91  79   90   65
stu22   69   70  89   96   84
stu23   89  100  76   58   76
stu24   68   84  98   90   76
stu25   77   66  57   80   96
stu26   79   81  61   99   84
stu27   71   51  70   95   61
stu28   52   67  96   78   62
stu29   63   72  60   91   99
stu30  100   62  83   66   77
stu31   71   91  53   84   59
stu32   63   61  65   99   56
stu33   97   67  67   95   96
stu34   79   53  55   97   95
stu35   79   79  69   85   89
stu36   67  100  79   72   69
stu37   55   92  89   62   52
stu38   74   54  88   75   50
stu39   86   80  58   97  100
stu40   64   88  71   66   68
stu41   58   60  52   59   63
stu42   57   76  66   59   55
stu43   90   86  90   82   72
stu44   51   77  97   50   60
stu45   72   55  63   92   64
stu46   73   87  85   99   83
stu47   67   98  86   53   64
stu48   61   88  51   50   67
stu49   97   81  56   91   66
stu50   62   51  90   66   88

In [16]:
df.iloc[-10:,:5]

       國文  英文  地理  人文  氣候
stu41  58  60  52  59  63
stu42  57  76  66  59  55
stu43  90  86  90  82  72
stu44  51  77  97  50  60
stu45  72  55  63  92  64
stu46  73  87  85  99  83
stu47  67  98  86  53  64
stu48  61  88  51  50  67
stu49  97  81  56  91  66
stu50  62  51  90  66  88