https://www.perplexity.ai/search/81642e0f-4214-4e4f-ba5a-a483c3484685

In [4]:
import pandas as pd

df = pd.read_csv("各鄉鎮市區人口密度.csv")
df

,statistic_yyy,site_id,people_total,area,population_density
0,統計年,區域別,年底人口數,土地面積,人口密度
1,106,新北市板橋區,551480,23.1373,23835
2,106,新北市三重區,387484,16.317,23747
3,106,新北市中和區,413590,20.144,20532
4,106,新北市永和區,222585,5.7138,38956
...,...,...,...,...,...
371,NaN,NaN,NaN,NaN,NaN
372,NaN,說明：1.人口密度係指每單位土地面積內之人口數。,NaN,NaN,NaN
373,NaN,2.96年12月起，我國土地面積增列東沙群島(2.38平方公里)及南沙群島(0.4896平方公里),NaN,NaN,NaN
374,NaN,，由高雄市代管；原金門縣烏坵鄉面積，因重測由2.6平方公里修正為1.2平方公里。,NaN,NaN,NaN
375,NaN,3.104年12月南沙太平島交通基礎整建工程竣工，增加面積0.0149平方公里。,NaN,NaN,NaN

In [5]:
import pandas as pd

df = pd.read_csv("各鄉鎮市區人口密度.csv")
df1 = df.rename(columns={"statistic_yyy":"統計年",
                   "site_id":"區域別",
                   "people_total":"年底人口數",
                   "area":"土地面積",
                   "population_density":"人口密度"
                   })
df1

,統計年,區域別,年底人口數,土地面積,人口密度
0,統計年,區域別,年底人口數,土地面積,人口密度
1,106,新北市板橋區,551480,23.1373,23835
2,106,新北市三重區,387484,16.317,23747
3,106,新北市中和區,413590,20.144,20532
4,106,新北市永和區,222585,5.7138,38956
...,...,...,...,...,...
371,NaN,NaN,NaN,NaN,NaN
372,NaN,說明：1.人口密度係指每單位土地面積內之人口數。,NaN,NaN,NaN
373,NaN,2.96年12月起，我國土地面積增列東沙群島(2.38平方公里)及南沙群島(0.4896平方公里),NaN,NaN,NaN
374,NaN,，由高雄市代管；原金門縣烏坵鄉面積，因重測由2.6平方公里修正為1.2平方公里。,NaN,NaN,NaN
375,NaN,3.104年12月南沙太平島交通基礎整建工程竣工，增加面積0.0149平方公里。,NaN,NaN,NaN

更改欄位名稱

In [7]:
df.columns = ["統計年","區域別","年底人口數","土地面積","人口密度"]
df

,統計年,區域別,年底人口數,土地面積,人口密度
0,統計年,區域別,年底人口數,土地面積,人口密度
1,106,新北市板橋區,551480,23.1373,23835
2,106,新北市三重區,387484,16.317,23747
3,106,新北市中和區,413590,20.144,20532
4,106,新北市永和區,222585,5.7138,38956
...,...,...,...,...,...
371,NaN,NaN,NaN,NaN,NaN
372,NaN,說明：1.人口密度係指每單位土地面積內之人口數。,NaN,NaN,NaN
373,NaN,2.96年12月起，我國土地面積增列東沙群島(2.38平方公里)及南沙群島(0.4896平方公里),NaN,NaN,NaN
374,NaN,，由高雄市代管；原金門縣烏坵鄉面積，因重測由2.6平方公里修正為1.2平方公里。,NaN,NaN,NaN
375,NaN,3.104年12月南沙太平島交通基礎整建工程竣工，增加面積0.0149平方公里。,NaN,NaN,NaN

刪除統計年

In [8]:
df2 = df.drop(["統計年"],axis=1)
df2

                                                   區域別   年底人口數     土地面積   人口密度
0                                                  區域別   年底人口數     土地面積   人口密度
1                                               新北市板橋區  551480  23.1373  23835
2                                               新北市三重區  387484   16.317  23747
3                                               新北市中和區  413590   20.144  20532
4                                               新北市永和區  222585   5.7138  38956
..                                                 ...     ...      ...    ...
371                                                NaN     NaN      NaN    NaN
372                           說明：1.人口密度係指每單位土地面積內之人口數。     NaN      NaN    NaN
373  2.96年12月起，我國土地面積增列東沙群島(2.38平方公里)及南沙群島(0.4896平方公里)     NaN      NaN    NaN
374           ，由高雄市代管；原金門縣烏坵鄉面積，因重測由2.6平方公里修正為1.2平方公里。     NaN      NaN    NaN
375           3.104年12月南沙太平島交通基礎整建工程竣工，增加面積0.0149平方公里。     NaN      NaN    NaN

[376 rows x 4 columns]

In [9]:
df3 = df2.dropna(axis=0)
df3

        區域別   年底人口數     土地面積   人口密度
0       區域別   年底人口數     土地面積   人口密度
1    新北市板橋區  551480  23.1373  23835
2    新北市三重區  387484   16.317  23747
3    新北市中和區  413590   20.144  20532
4    新北市永和區  222585   5.7138  38956
..      ...     ...      ...    ...
366  連江縣北竿鄉    2360      9.9    238
367  連江縣莒光鄉    1624      4.7    346
368  連江縣東引鄉    1352      3.8    356
369    東沙群島      …      2.38     …
370    南沙群島      …    0.5045     …

[371 rows x 4 columns]

In [72]:
df4 = df3.drop(index=0)
df4

        區域別   年底人口數     土地面積   人口密度
1    新北市板橋區  551480  23.1373  23835
2    新北市三重區  387484   16.317  23747
3    新北市中和區  413590   20.144  20532
4    新北市永和區  222585   5.7138  38956
5    新北市新莊區  416524  19.7383  21102
..      ...     ...      ...    ...
366  連江縣北竿鄉    2360      9.9    238
367  連江縣莒光鄉    1624      4.7    346
368  連江縣東引鄉    1352      3.8    356
369    東沙群島      …      2.38     …
370    南沙群島      …    0.5045     …

[370 rows x 4 columns]

In [74]:
df4.info()

<class 'pandas.core.frame.DataFrame'>
Index: 370 entries, 1 to 370
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   區域別     370 non-null    object
 1   年底人口數   370 non-null    object
 2   土地面積    370 non-null    object
 3   人口密度    370 non-null    object
dtypes: object(4)
memory usage: 14.5+ KB

In [75]:
# df4['年底人口數'].astype(int) #無法轉換
def string_to_int(value:str):
    try:
        v = int(value)
        return v
    except Exception:
        return 0
    
df4["年底人口數"] = df4["年底人口數"].map(string_to_int)
df4["人口密度"] = df4["人口密度"].apply(string_to_int)

In [77]:
df4.info()

<class 'pandas.core.frame.DataFrame'>
Index: 370 entries, 1 to 370
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   區域別     370 non-null    object
 1   年底人口數   370 non-null    int64
 2   土地面積    370 non-null    object
 3   人口密度    370 non-null    int64
dtypes: int64(2), object(2)
memory usage: 14.5+ KB

In [78]:
df4['土地面積'] = df4['土地面積'].astype(float)

In [79]:
df4.info()

<class 'pandas.core.frame.DataFrame'>
Index: 370 entries, 1 to 370
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   區域別     370 non-null    object
 1   年底人口數   370 non-null    int64
 2   土地面積    370 non-null    float64
 3   人口密度    370 non-null    int64
dtypes: float64(1), int64(2), object(1)
memory usage: 14.5+ KB

In [80]:
df4

        區域別   年底人口數     土地面積   人口密度
1    新北市板橋區  551480  23.1373  23835
2    新北市三重區  387484  16.3170  23747
3    新北市中和區  413590  20.1440  20532
4    新北市永和區  222585   5.7138  38956
5    新北市新莊區  416524  19.7383  21102
..      ...     ...      ...    ...
366  連江縣北竿鄉    2360   9.9000    238
367  連江縣莒光鄉    1624   4.7000    346
368  連江縣東引鄉    1352   3.8000    356
369    東沙群島       0   2.3800      0
370    南沙群島       0   0.5045      0

[370 rows x 4 columns]

In [51]:
df4.iloc[:,0]

1      新北市板橋區
2      新北市三重區
3      新北市中和區
4      新北市永和區
5      新北市新莊區
        ...
366    連江縣北竿鄉
367    連江縣莒光鄉
368    連江縣東引鄉
369      東沙群島
370      南沙群島
Name: 區域別, Length: 370, dtype: object

In [81]:
df4['區域別']

1      新北市板橋區
2      新北市三重區
3      新北市中和區
4      新北市永和區
5      新北市新莊區
        ...
366    連江縣北竿鄉
367    連江縣莒光鄉
368    連江縣東引鄉
369      東沙群島
370      南沙群島
Name: 區域別, Length: 370, dtype: object

In [55]:
def split_words(v:str):
    print (len(v))
    return v
       
df4['區域別'].map(split_words)

6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
5
5
5
5
5
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
5
5
5
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
7
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
7
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
7
6
6
6
6
6
6
6
6
6
6
6
6
7
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
5
5
6
5
5
6
6
6
6
6
6
6
6
6
6
4
4

1      新北市板橋區
2      新北市三重區
3      新北市中和區
4      新北市永和區
5      新北市新莊區
        ...
366    連江縣北竿鄉
367    連江縣莒光鄉
368    連江縣東引鄉
369      東沙群島
370      南沙群島
Name: 區域別, Length: 370, dtype: object

In [82]:
def split_words(v:str):
    if len(v) == 6:
        return v[:3]
    else:
        return v

df4['區域別'].map(split_words)

1       新北市
2       新北市
3       新北市
4       新北市
5       新北市
       ...
366     連江縣
367     連江縣
368     連江縣
369    東沙群島
370    南沙群島
Name: 區域別, Length: 370, dtype: object

In [83]:
def split_words(v:str):
    if len(v) == 6:
        return v[:3]
    else:
        return v

df4["縣市"] = df4['區域別'].map(split_words)

In [84]:
def split_area(v:str):
    if len(v) == 6:
        return v[-3:]
    else:
        return v
df4['區域別'].map(split_area)

1       板橋區
2       三重區
3       中和區
4       永和區
5       新莊區
       ...
366     北竿鄉
367     莒光鄉
368     東引鄉
369    東沙群島
370    南沙群島
Name: 區域別, Length: 370, dtype: object

In [85]:
def split_area(v:str):
    if len(v) == 6:
        return v[-3:]
    else:
        return v
df4['區域別'] = df4['區域別'].map(split_area)

In [86]:
df4

      區域別   年底人口數     土地面積   人口密度    縣市
1     板橋區  551480  23.1373  23835   新北市
2     三重區  387484  16.3170  23747   新北市
3     中和區  413590  20.1440  20532   新北市
4     永和區  222585   5.7138  38956   新北市
5     新莊區  416524  19.7383  21102   新北市
..    ...     ...      ...    ...   ...
366   北竿鄉    2360   9.9000    238   連江縣
367   莒光鄉    1624   4.7000    346   連江縣
368   東引鄉    1352   3.8000    356   連江縣
369  東沙群島       0   2.3800      0  東沙群島
370  南沙群島       0   0.5045      0  南沙群島

[370 rows x 5 columns]

In [62]:
df5 = df4.reindex(columns=["區域別","縣市","年底人口數","土地面積","人口密度"])
df5

      區域別    縣市   年底人口數     土地面積   人口密度
1     板橋區   板橋區  551480  23.1373  23835
2     三重區   三重區  387484  16.3170  23747
3     中和區   中和區  413590  20.1440  20532
4     永和區   永和區  222585   5.7138  38956
5     新莊區   新莊區  416524  19.7383  21102
..    ...   ...     ...      ...    ...
366   北竿鄉   北竿鄉    2360   9.9000    238
367   莒光鄉   莒光鄉    1624   4.7000    346
368   東引鄉   東引鄉    1352   3.8000    356
369  東沙群島  東沙群島       0   2.3800      0
370  南沙群島  南沙群島       0   0.5045      0

[370 rows x 5 columns]

In [63]:
df5 = df4.reindex(columns=["區域別","縣市","年底人口數","土地面積","人口密度"])
df6 = df5.set_index('區域別')
df6

        縣市   年底人口數     土地面積   人口密度
區域別
板橋區    板橋區  551480  23.1373  23835
三重區    三重區  387484  16.3170  23747
中和區    中和區  413590  20.1440  20532
永和區    永和區  222585   5.7138  38956
新莊區    新莊區  416524  19.7383  21102
...    ...     ...      ...    ...
北竿鄉    北竿鄉    2360   9.9000    238
莒光鄉    莒光鄉    1624   4.7000    346
東引鄉    東引鄉    1352   3.8000    356
東沙群島  東沙群島       0   2.3800      0
南沙群島  南沙群島       0   0.5045      0

[370 rows x 4 columns]

In [87]:
df6.to_excel('各鄉鎮市區人口密度.xlsx',index=True)